name: SignCommands
main: fun.sunrisemc.sign_commands.SignCommandsPlugin
version: 1.0.0
api-version: 1.18
author: TheFishNextDoor
description: Allows assigning commands to signs.
commands:
  signcommands:
    description: Main plugin command
    usage: /signcommands <subcommand>
    permission: signcommands.use
    aliases: [sc]
  signedit:
    description: Edit a sign.
    usage: /signedit <subcommand>
    permission: signedit.use
    aliases: [se, editsign]
permissions:
  signcommands.use:
    description: Allows the player to use command signs.
  signcommands.admin.reload:
    description: Allows the player to reload the SignCommands configuration.
  signcommands.admin.info:
    description: Allows the player to view information about a command sign.
  signcommands.admin.list:
    description: Allows the player to list all command signs.
  signcommands.admin.goto:
    description: Allows the player to teleport to a command sign.
  signcommands.admin.rename:
    description: Allows the player to rename a command sign.
  signcommands.admin.delete:
    description: Allows the player to delete a command sign.
  signcommands.admin.commands:
    description: Allows the player to manage commands on command signs.
  signcommands.admin.permissions:
    description: Allows the player to manage permissions on command signs.
  signcommands.admin.globalclickcooldown:
    description: Allows the player to manage the global click cooldown on command signs.
  signcommands.admin.globalmaxclicks:
    description: Allows the player to manage the global max clicks on command signs.
  signcommands.admin.userclickcooldown:
    description: Allows the player to manage the user click cooldown on command signs.
  signcommands.admin.usermaxclicks:
    description: Allows the player to manage the user max clicks on command signs.
  signcommands.admin.clickcost:
    description: Allows the player to manage the click cost on command signs.
  signedit.use:
    description: Allows the player to use the sign edit commands.
  signedit.color:
    description: Allows use of color codes on signs.
  signedit.bypassprotections:
    description: Allows bypassing protections when editing signs.