name: SignCommands
main: fun.sunrisemc.sign_commands.SignCommandsPlugin
version: 1.0.0
api-version: 1.18
author: TheFishNextDoor
description: Allows assigning commands to signs.
commands:
  signcommands:
    description: Main plugin command
    usage: /signcommands <subcommand>
    permission: signcommands.use
    aliases: [sc]
  signedit:
    description: Edit a sign.
    usage: /signedit <subcommand>
    permission: signedit.use
permissions:
  signcommands.use:
    description: Allows the player to use command signs.
  signcommands.reload:
    description: Allows use of the reload command.
  signcommands.rename:
    description: Allows renaming of command signs.
  signcommands.list:
    description: Allows listing of command signs.
  signcommands.goto:
    description: Allows teleporting to command signs.
  signcommands.managecommands:
    description: Allows managing commands on command signs.
  signcommands.managerequiredpermission:
    description: Allows managing required permissions for command signs.
  signcommands.manageblockedpermission:
    description: Allows managing blocked permissions for command signs.
  signcommands.color:
    description: Allows use of color codes on signs.
  signedit.use:
    description: Allows the player to use the sign edit commands.