name: SignCommands
main: fun.sunrisemc.sign_commands.SignCommandsPlugin
version: 1.0.0
api-version: 1.20
author: TheFishNextDoor
description: Allows assigning commands to signs.
commands:
  signcommands:
    description: Main plugin command
    usage: /signcommands <subcommand>
    permission: signcommands.use
    aliases: [sc]
permissions:
  signcommands.use:
    description: Allows the player to use command signs.
  signcommands.reload:
    description: Allows use of the reload command.
  signcommands.add:
    description: Allows adding sign commands.
  signcommands.remove:
    description: Allows removing sign commands.
  signcommands.listcommands:
    description: Allows listing sign commands.
  signcommands.listsigns:
    description: Allows listing command signs.
  signcommands.goto:
    description: Allows teleporting to a command sign.