name: SignCommands
main: fun.sunrisemc.sign_commands.SignCommandsPlugin
version: 1.0.0
api-version: 1.18
author: TheFishNextDoor
description: Allows assigning commands to signs.
commands:
  signcommands:
    description: Main plugin command
    usage: /signcommands <subcommand>
    permission: signcommands
    aliases: [ex]
permissions:
  signcommands.reload:
    description: Allows use of the reload command
  signcommands.add:
    description: Allows adding sign commands
  signcommands.remove:
    description: Allows removing sign commands
  signcommands.list:
    description: Allows listing sign commands